# Generated by Django 2.2.7 on 2020-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0015_auto_20170617_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgallery',
            name='bootstrap4_column_class',
            field=models.CharField(blank=True, default='col-lg-3', max_length=255, verbose_name='Bootstrap4 column class'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='bootstrap4_container_class',
            field=models.CharField(blank=True, default='container', max_length=255, verbose_name='Bootstrap4 container class'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='bootstrap4_row_class',
            field=models.CharField(blank=True, default='row', max_length=255, verbose_name='Bootstrap4 row class'),
        ),
    ]
