# Generated by Django 2.2.7 on 2020-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0016_auto_20200222_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgallery',
            name='crop',
            field=models.BooleanField(default=True, verbose_name='Превью резать до стандартного размера?'),
        ),
    ]
