# Generated by Django 2.2.7 on 2020-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0017_lightgallery_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightgallery',
            name='bootstrap4_container_class',
        ),
        migrations.AlterField(
            model_name='lightgallery',
            name='bootstrap4_column_class',
            field=models.CharField(blank=True, default='col-lg-3', max_length=255, verbose_name='Bootstrap4 column class'),
        ),
    ]
